# -*- coding: utf-8 -*-
"""AmazonMlChallenge2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GVIU5NOGhakjZHgWqSuqKSjy5oWn41T
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from lightgbm import LGBMRegressor
from sentence_transformers import SentenceTransformer

train = pd.read_csv("train.csv")
test  = pd.read_csv("test.csv")

print("Train shape:", train.shape)
print("Test shape:", test.shape)


train['price'] = train['price'].clip(lower=0.01)
y_train = np.log1p(train['price'])  # log(1 + price) transformation


train_corpus = train['catalog_content'].fillna('')
test_corpus  = test['catalog_content'].fillna('')


tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2), stop_words='english')
X_train_tfidf = tfidf.fit_transform(train_corpus)
X_test_tfidf  = tfidf.transform(test_corpus)


model_st = SentenceTransformer('all-MiniLM-L6-v2')

train_emb = model_st.encode(train_corpus.tolist(), batch_size=64, show_progress_bar=True)
test_emb  = model_st.encode(test_corpus.tolist(), batch_size=64, show_progress_bar=True)


train_feats = pd.DataFrame({
    'text_len': train_corpus.str.len(),
    'word_count': train_corpus.str.split().str.len(),
    'digit_count': train_corpus.str.count(r'\d')
})
test_feats = pd.DataFrame({
    'text_len': test_corpus.str.len(),
    'word_count': test_corpus.str.split().str.len(),
    'digit_count': test_corpus.str.count(r'\d')
})


X_train_full = np.hstack([train_emb, train_feats.values])
X_test_full  = np.hstack([test_emb, test_feats.values])


mask = ~np.isnan(y_train)
X_train_clean = X_train_full[mask]
y_train_clean = y_train[mask]

model = LGBMRegressor(
    n_estimators=500,
    learning_rate=0.05,
    num_leaves=31,
    random_state=42
)

model.fit(X_train_clean, y_train_clean)
print("✅ Model training complete!")


y_pred_log = model.predict(X_test_full)
y_pred = np.expm1(y_pred_log)  # inverse log1p


submission = pd.DataFrame({
    "sample_id": test["sample_id"],
    "price": y_pred
})

print("Number of rows in submission:", len(submission))  # should be 75,000
submission.to_csv("test_out.csv", index=False)
print("✅ Submission file created!")



print(len(submission))